sudo: false
language: node_js
node_js:
- 6
- 8
- 'stable'
# gh-pagesへのdeploy向け
env:
  global:
    - GH_USER_EMAIL="azuciao@gmail.com"
    - GH_USER_NAME="azu"
jobs:
  include:
    # Unit Tests
    - stage: test
      node_js: 'stable'
      script: npm run travis
    - stage: test
      node_js: 'lts/*'
      script: npm test
    # deploy
    - stage: deploy
      if: branch = master AND type != pull_request
      before_script:
        - |
        
          $(npm bin)/set-up-ssh --key "$encrypted_55887fb399d9_key" \
                                --iv "$encrypted_55887fb399d9_iv" \
                                --path-encrypted-key ".travis/github_deploy_key.enc"
      script:
        - |
        
          $(npm bin)/update-branch --commands "npm run build" \
                             --commit-message "Deploy GitBook build [skip ci]" \
                             --directory "_book" \
                             --distribution-branch "gh-pages" \
                             --source-branch "master"
