sudo: required
addons:
  chrome: stable
language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install --ignore-scripts
env:
  global:
    # gh-pagesへのdeploy向け
    - GH_USER_EMAIL="azuciao@gmail.com"
    - GH_USER_NAME="azu"
jobs:
  include:
    # Unit Tests
    - stage: test
      node_js: 'stable'
      script: npm run travis
    - stage: test
      node_js: '6'
      script: npm test
    - stage: test
      node_js: '8'
      script: npm test
    # deploy
    - stage: deploy
      node_js: 'stable'
      if: branch = master AND type != pull_request
      before_script:
        - |

          $(npm bin)/set-up-ssh --key "$encrypted_55887fb399d9_key" \
                                --iv "$encrypted_55887fb399d9_iv" \
                                --path-encrypted-key ".travis/github_deploy_key.enc"
      script:
        - |
          npm run install:gitbook
          $(npm bin)/update-branch --commands "npm run build" \
                             --commit-message "Deploy GitBook build [skip ci]" \
                             --directory "_book" \
                             --distribution-branch "gh-pages" \
                             --source-branch "master"
