sudo: required
addons:
  chrome: stable
language: node_js
env:
  global:
    # gh-pagesへのdeploy向け
    - GH_USER_EMAIL="azuciao@gmail.com"
    - GH_USER_NAME="azu"
jobs:
  include:
    # Unit Tests
    - stage: test
      name: "Unit Tests on Node.js 10"
      node_js: '10'
      script: npm run travis
    - stage: test
      name: "Unit Tests on Node.js 8"
      node_js: '8'
      script: npm test
    # E2E
    - stage: test
      name: "E2E Tests"
      # masterのみ実行
      if: branch = master AND type != pull_request
      node_js: '10'
      script: npm run e2e
    # deploy
    - stage: deploy
      node_js: '10'
      if: branch = master AND type != pull_request
      before_script:
        - |

          $(npm bin)/set-up-ssh --key "$encrypted_55887fb399d9_key" \
                                --iv "$encrypted_55887fb399d9_iv" \
                                --path-encrypted-key ".travis/github_deploy_key.enc"
      script:
        - |
          npm run install:gitbook
          $(npm bin)/update-branch --commands "npm run build" \
                             --commit-message "Deploy GitBook build [skip ci]" \
                             --directory "_book" \
                             --distribution-branch "gh-pages" \
                             --source-branch "master"
