name: test
on:
  push:
    branches-ignore:
      - 'publish1' # srcはテストしても意味がないため
  pull_request:
    branches-ignore:
      - 'publish1' # srcはテストしても意味がないため

env:
  CI: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x,]
        os: [macOS-10.14, windows-latest, ubuntu-18.04]
    name: "Build on Node.js: ${{ matrix.node-version }} OS: ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: "Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 12.x, 10.x]
    name: "Test on Node.js ${{ matrix.node-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: "Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
  e2e:
    runs-on: ubuntu-latest
    name: E2E
    steps:
      - uses: actions/checkout@v2
      - name: Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run e2e
